{% set version = '0.22-1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-afex
  version: {{ version|replace("-", "_") }}

source:
  fn: afex_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/afex_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/afex/afex_{{ version }}.tar.gz
  sha256: 16c9abf4f8b9f695704a0313e1b2b5ab1ae6dd75f71126d8c6ff1c2a695fbc18

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-car
    - r-lme4 >=1.1_8
    - r-lmertest >=3.0_0
    - r-pbkrtest >=0.4_1
    - r-reshape2
  run:
    - r-base
    - r-car
    - r-lme4 >=1.1_8
    - r-lmertest >=3.0_0
    - r-pbkrtest >=0.4_1
    - r-reshape2

test:
  commands:
    - $R -e "library('afex')"           # [not win]
    - "\"%R%\" -e \"library('afex')\""  # [win]

about:
  home: http://afex.singmann.science/, https://github.com/singmann/afex
  license: GPL (>= 2)
  summary: Convenience functions for analyzing factorial experiments using ANOVA or mixed models.
    aov_ez(), aov_car(), and aov_4() allow specification of between, within (i.e., repeated-measures),
    or mixed (i.e., split-plot)  ANOVAs for data in long format (i.e., one observation
    per row), automatically aggregating multiple observations per individual and cell  of
    the design. mixed() fits mixed models using lme4::lmer() and computes  p-values
    for all fixed effects using either Kenward-Roger or Satterthwaite  approximation
    for degrees of freedom (LMM only), parametric bootstrap  (LMMs and GLMMs), or likelihood
    ratio tests (LMMs and GLMMs).  afex_plot() provides a high-level interface for interaction
    or one-way  plots using ggplot2, combining raw data and model estimates. afex uses  type
    3 sums of squares as default (imitating commercial statistical software).
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
