{% set version = "0.28-0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-afex
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/afex_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/afex/afex_{{ version }}.tar.gz
  sha256: 9191ec35e670059b389f8247a96582f28b1a5c85be4fb81559827f4a055e8730

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-car
    - r-lme4 >=1.1_8
    - r-lmertest >=3.0_0
    - r-pbkrtest >=0.4_1
    - r-reshape2
  run:
    - r-base
    - r-car
    - r-lme4 >=1.1_8
    - r-lmertest >=3.0_0
    - r-pbkrtest >=0.4_1
    - r-reshape2

test:
  commands:
    - $R -e "library('afex')"           # [not win]
    - "\"%R%\" -e \"library('afex')\""  # [win]

about:
  home: http://afex.singmann.science/, https://github.com/singmann/afex
  license: GPL-2.0-or-later
  summary: Convenience functions for analyzing factorial experiments using ANOVA or mixed models. aov_ez(), aov_car(), and aov_4() allow specification of between, within (i.e., repeated-measures), or mixed (i.e., split-plot)  ANOVAs for data in long format (i.e., one observation per row), automatically aggregating multiple
    observations per individual and cell  of the design. mixed() fits mixed models using lme4::lmer() and computes  p-values for all fixed effects using either Kenward-Roger or Satterthwaite  approximation for degrees of freedom (LMM only), parametric bootstrap  (LMMs and GLMMs), or likelihood ratio tests (LMMs and GLMMs).  afex_plot()
    provides a high-level interface for interaction or one-way  plots using ggplot2, combining raw data and model estimates. afex uses  type 3 sums of squares as default (imitating commercial statistical software).
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: afex
# Type: Package
# Title: Analysis of Factorial Experiments
# Depends: R (>= 3.1.0), lme4 (>= 1.1-8)
# Suggests: emmeans (>= 1.4), coin, xtable, parallel, plyr, optimx, nloptr, knitr, rmarkdown, R.rsp, lattice, latticeExtra, multcomp, testthat, mlmRev, dplyr, tidyr, dfoptim, Matrix, psych, ggplot2, MEMSS, effects, carData, ggbeeswarm, nlme, cowplot, jtools, ggpubr, ggpol, MASS, glmmTMB, brms, rstanarm
# Imports: pbkrtest (>= 0.4-1), lmerTest (>= 3.0-0), car, reshape2, stats, methods, utils
# Description: Convenience functions for analyzing factorial experiments using ANOVA or mixed models. aov_ez(), aov_car(), and aov_4() allow specification of between, within (i.e., repeated-measures), or mixed (i.e., split-plot)  ANOVAs for data in long format (i.e., one observation per row), automatically aggregating multiple observations per individual and cell  of the design. mixed() fits mixed models using lme4::lmer() and computes  p-values for all fixed effects using either Kenward-Roger or Satterthwaite  approximation for degrees of freedom (LMM only), parametric bootstrap  (LMMs and GLMMs), or likelihood ratio tests (LMMs and GLMMs).  afex_plot() provides a high-level interface for interaction or one-way  plots using ggplot2, combining raw data and model estimates. afex uses  type 3 sums of squares as default (imitating commercial statistical software).
# URL: http://afex.singmann.science/, https://github.com/singmann/afex
# BugReports: https://github.com/singmann/afex/issues
# License: GPL (>= 2)
# Encoding: UTF-8
# VignetteBuilder: knitr, R.rsp
# Authors@R: c(person(given="Henrik", family="Singmann", role=c("aut", "cre"), email="singmann+afex@gmail.com", comment=c(ORCID="0000-0002-4842-3657")), person(given="Ben", family="Bolker", role=c("aut")),  person(given="Jake",family="Westfall", role=c("aut")),  person(given="Frederik", family="Aust", role=c("aut"),  comment = c(ORCID = "0000-0003-4900-788X")), person(given="Mattan S.",family="Ben-Shachar", role=c("aut")),  person(given="Sren", family="Hjsgaard", role=c("ctb")), person(given="John", family="Fox", role=c("ctb")),  person(given="Michael A.", family="Lawrence", role=c("ctb")),  person(given="Ulf", family="Mertens", role=c("ctb")),  person(given="Jonathon", family="Love", role=c("ctb")),  person(given="Russell", family="Lenth", role=c("ctb")),  person(given="Rune", family="Haubo Bojesen Christensen", role=c("ctb")))
# Version: 0.25-1
# RoxygenNote: 6.1.1
# LazyData: true
# NeedsCompilation: no
# Packaged: 2019-08-27 16:58:58 UTC; henrik
# Author: Henrik Singmann [aut, cre] (<https://orcid.org/0000-0002-4842-3657>), Ben Bolker [aut], Jake Westfall [aut], Frederik Aust [aut] (<https://orcid.org/0000-0003-4900-788X>), Mattan S. Ben-Shachar [aut], Sren Hjsgaard [ctb], John Fox [ctb], Michael A. Lawrence [ctb], Ulf Mertens [ctb], Jonathon Love [ctb], Russell Lenth [ctb], Rune Haubo Bojesen Christensen [ctb]
# Maintainer: Henrik Singmann <singmann+afex@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-08-27 18:10:02 UTC
